#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
run_id="${AGENT_GEST_JJ_GITHUB_RUN_ID:-$(date -u +%Y%m%dT%H%M%SZ)-$$}"
lab_root="${AGENT_GEST_JJ_GITHUB_LAB:-/tmp/agent-gest-jj-live-github-lab-$run_id}"
owner="${AGENT_GEST_JJ_GITHUB_OWNER:-}"
visibility="${AGENT_GEST_JJ_GITHUB_VISIBILITY:-private}"
repo_prefix="${AGENT_GEST_JJ_GITHUB_REPO_PREFIX:-agent-gest-jj-live}"
keep_repos="${AGENT_GEST_JJ_KEEP_GITHUB_REPOS:-0}"
logs_dir="$lab_root/logs"
tutorial="$lab_root/jj-live-github-workflow-tutorial.md"
jst_bin="$repo_root/node_modules/.bin/jst"

created_repos=()
created_dirs=()
made_full_repo=""
made_dir=""

usage() {
  cat <<'USAGE'
Usage: scripts/run_jj_github_integration_lab.sh

Runs the four jj parity examples against four separate temporary GitHub repos:

1. Plain bookmark review flow
2. Multi-commit bookmark review flow
3. LazyJJ + jj-stack stacked PR flow
4. Parallel jj workspace flow

The script requires authenticated GitHub CLI access and the delete_repo scope
because it destroys the temporary repos with `gh repo delete --yes`.

Optional environment:
  AGENT_GEST_JJ_GITHUB_OWNER=<owner>        GitHub user/org for temp repos
  AGENT_GEST_JJ_GITHUB_VISIBILITY=private  private|public, default private
  AGENT_GEST_JJ_GITHUB_LAB=/tmp/path       output/log directory
  AGENT_GEST_JJ_KEEP_GITHUB_REPOS=1        keep repos for debugging
USAGE
}

die() {
  echo "error: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

cleanup() {
  status=$?
  set +u
  if [ "$keep_repos" = "1" ]; then
    echo "Keeping GitHub repos because AGENT_GEST_JJ_KEEP_GITHUB_REPOS=1:" >&2
    if [ "${#created_repos[@]}" -gt 0 ]; then
      printf '  %s\n' "${created_repos[@]}" >&2
    fi
    exit "$status"
  fi

  [ -d "$logs_dir" ] || mkdir -p "$logs_dir"
  for full_repo in "${created_repos[@]}"; do
    echo "Deleting temporary GitHub repo: $full_repo" >&2
    gh repo delete "$full_repo" --yes >>"$logs_dir/cleanup.log" 2>&1 || {
      echo "warning: failed to delete $full_repo; see $logs_dir/cleanup.log" >&2
    }
  done

  for dir in "${created_dirs[@]}"; do
    rm -rf "$dir"
  done

  exit "$status"
}

case "${1:-}" in
  -h|--help)
    usage
    exit 0
    ;;
esac

trap cleanup EXIT

case "$visibility" in
  private|public) ;;
  *) die "AGENT_GEST_JJ_GITHUB_VISIBILITY must be private or public" ;;
esac

mkdir -p "$logs_dir"

require_command git
require_command gh
require_command jj
require_command just

if [ ! -x "$jst_bin" ]; then
  die "missing jj-stack binary at $jst_bin; run just setup"
fi

auth_status="$(gh auth status -h github.com 2>&1)" || {
  printf '%s\n' "$auth_status" >&2
  die "gh is not authenticated; run gh auth login"
}

printf '%s\n' "$auth_status" >"$logs_dir/gh-auth-status.log"
if ! printf '%s\n' "$auth_status" | grep -q "delete_repo"; then
  die "gh is authenticated but lacks delete_repo scope; run: gh auth refresh -h github.com -s delete_repo"
fi

if [ -z "$owner" ]; then
  owner="$(gh api user -q .login)"
fi

cat >"$tutorial" <<EOF
# Live GitHub JJ Workflow Lab

Run ID: \`$run_id\`

Owner: \`$owner\`

This tutorial trace was generated by running each jj parity example against a
separate temporary GitHub repository. The repositories are deleted at the end of
the run with \`gh repo delete --yes\`.

EOF

append_tutorial() {
  cat >>"$tutorial"
}

log_cmd() {
  printf '\n$'
  printf ' %q' "$@"
  printf '\n'
  "$@"
}

write_file() {
  local path="$1"
  shift
  printf '%s\n' "$@" >"$path"
  printf '\n$ printf ... > %q\n' "$path"
}

make_repo() {
  local slug="$1"
  local repo_name="$repo_prefix-$run_id-$slug"
  local full_repo="$owner/$repo_name"
  local dir="$lab_root/$slug"

  mkdir -p "$dir"
  created_dirs+=("$dir")
  created_repos+=("$full_repo")

  (
    cd "$dir"
    log_cmd git init
    log_cmd gh repo create "$full_repo" "--$visibility" --source=. --remote=origin --disable-issues --disable-wiki
    log_cmd jj git init --colocate
  )

  made_full_repo="$full_repo"
  made_dir="$dir"
}

init_main() {
  write_file README.md "# $1"
  mkdir -p src
  write_file src/app.txt "base"
  log_cmd jj diff
  log_cmd jj describe -m "chore: initialize $1"
  log_cmd jj new
  log_cmd jj bookmark set main -r @-
  log_cmd jj git push --bookmark main
  log_cmd jj bookmark list --all
}

verify_main_tracking() {
  jj bookmark list --all | grep -A2 '^main:' | grep -q '@origin' ||
    die "expected main to have @origin tracking"
}

run_flow() {
  local slug="$1"
  local title="$2"
  local func="$3"
  local log="$logs_dir/$slug.log"

  echo "Running $title"
  append_tutorial <<EOF
## $title

Full command log: \`$log\`

EOF

  {
    echo "# $title"
    "$func"
  } >"$log" 2>&1

  append_tutorial <<EOF
\`\`\`text
$(tail -n 80 "$log")
\`\`\`

EOF
}

flow_plain_bookmark() {
  local full_repo dir
  make_repo "plain-bookmark"
  full_repo="$made_full_repo"
  dir="$made_dir"
  cd "$dir"
  init_main "plain bookmark"
  verify_main_tracking

  log_cmd jj new main
  write_file plain.txt "plain bookmark change"
  log_cmd jj commit -m "test: add plain bookmark change"
  log_cmd jj bookmark set demo/plain-bookmark -r @-
  log_cmd jj git push --bookmark demo/plain-bookmark
  log_cmd gh pr create --repo "$full_repo" --base main --head demo/plain-bookmark --title "test: plain bookmark flow" --body "Live jj plain bookmark flow."
  log_cmd gh pr view demo/plain-bookmark --repo "$full_repo" --json number,url,state,mergeable,headRefName,baseRefName
}

flow_multi_commit() {
  local full_repo dir count
  make_repo "multi-commit"
  full_repo="$made_full_repo"
  dir="$made_dir"
  cd "$dir"
  init_main "multi commit"
  verify_main_tracking

  log_cmd jj new main
  write_file session.txt "session edit one"
  log_cmd jj commit -m "test: add first session edit"
  printf 'session edit two\n' >> session.txt
  printf '\n$ printf ... >> session.txt\n'
  log_cmd jj commit -m "test: add second session edit"
  log_cmd jj bookmark set demo/session-bookmark -r @-
  log_cmd jj git push --bookmark demo/session-bookmark
  count="$(jj log -r 'main..bookmarks(exact:"demo/session-bookmark")' --no-graph --no-pager -T 'commit_id ++ "\n"' | wc -l | tr -d ' ')"
  [ "$count" -ge 2 ] || die "expected at least two commits in multi-commit flow"
  log_cmd gh pr create --repo "$full_repo" --base main --head demo/session-bookmark --title "test: multi-commit bookmark flow" --body "Live jj multi-commit bookmark flow."
  log_cmd gh pr view demo/session-bookmark --repo "$full_repo" --json number,url,state,mergeable,headRefName,baseRefName,commits
}

flow_lazyjj_stack() {
  local full_repo dir pr_count
  make_repo "lazyjj-stack"
  full_repo="$made_full_repo"
  dir="$made_dir"
  cd "$dir"
  init_main "lazyjj stack"
  verify_main_tracking

  for alias_name in start create stack ss prs; do
    log_cmd jj config get "aliases.$alias_name"
  done

  log_cmd jj start
  write_file stack.txt "stack base"
  log_cmd jj commit -m "test: add stack base"
  log_cmd jj create demo/stack-base
  printf 'stack child\n' >> stack.txt
  printf '\n$ printf ... >> stack.txt\n'
  log_cmd jj commit -m "test: add stack child"
  log_cmd jj create demo/stack-child
  log_cmd jj stack --no-pager
  log_cmd jj ss
  log_cmd "$jst_bin" submit demo/stack-child
  log_cmd jj prs
  log_cmd gh pr list --repo "$full_repo" --state open --json number,url,title,headRefName,baseRefName
  pr_count="$(gh pr list --repo "$full_repo" --state open --json number --jq 'length')"
  [ "$pr_count" -eq 2 ] || die "expected two stacked PRs, got $pr_count"
}

flow_jj_workspaces() {
  local full_repo dir workspace_a workspace_b pr_count
  make_repo "jj-workspaces"
  full_repo="$made_full_repo"
  dir="$made_dir"
  cd "$dir"
  init_main "jj workspaces"
  verify_main_tracking

  workspace_a="$lab_root/jj-workspaces-a"
  workspace_b="$lab_root/jj-workspaces-b"
  created_dirs+=("$workspace_a" "$workspace_b")

  log_cmd jj workspace add "$workspace_a" --name live-workspace-a -r main
  log_cmd jj workspace add "$workspace_b" --name live-workspace-b -r main

  (
    cd "$workspace_a"
    write_file workspace-a.txt "workspace a isolated change"
    log_cmd jj commit -m "test: add workspace a change"
    log_cmd jj bookmark set demo/workspace-a -r @-
    log_cmd jj git push --bookmark demo/workspace-a
    log_cmd gh pr create --repo "$full_repo" --base main --head demo/workspace-a --title "test: workspace a flow" --body "Live jj workspace A flow."
  )

  (
    cd "$workspace_b"
    write_file workspace-b.txt "workspace b isolated change"
    log_cmd jj commit -m "test: add workspace b change"
    log_cmd jj bookmark set demo/workspace-b -r @-
    log_cmd jj git push --bookmark demo/workspace-b
    log_cmd gh pr create --repo "$full_repo" --base main --head demo/workspace-b --title "test: workspace b flow" --body "Live jj workspace B flow."
  )

  log_cmd jj log -r 'description("workspace a") | description("workspace b")' --no-pager
  log_cmd gh pr list --repo "$full_repo" --state open --json number,url,title,headRefName,baseRefName
  pr_count="$(gh pr list --repo "$full_repo" --state open --json number --jq 'length')"
  [ "$pr_count" -eq 2 ] || die "expected two workspace PRs, got $pr_count"
  log_cmd jj workspace forget live-workspace-a
  log_cmd jj workspace forget live-workspace-b
}

run_flow "plain-bookmark" "Flow 1: Plain JJ Bookmark Review" flow_plain_bookmark
run_flow "multi-commit" "Flow 2: Multi-Commit Bookmark Review" flow_multi_commit
run_flow "lazyjj-stack" "Flow 3: LazyJJ And JJ-Stack PR Stack" flow_lazyjj_stack
run_flow "jj-workspaces" "Flow 4: Parallel JJ Workspaces" flow_jj_workspaces

echo "live GitHub jj workflow lab passed"
echo "tutorial trace: $tutorial"
echo "logs: $logs_dir"
